stages:
- build_deb
- build_image

buid_deb:
  stage: build_deb
  tags:
  - docker
  script:
  - /build.sh
  image: hsmade/svxlink-buildpackage 
  artifacts:
    paths:
    - out.deb

build_image:
  stage: build_image
  tags: 
  - vps
  image: docker:git
  services:
  - docker:dind
  script:
  - ls 
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE .
  - docker push $CI_REGISTRY_IMAGE:latest
